### ISSUE TITLE
Proposal

### ISSUE THREAD

**Issue by jteresco** [adamdachenhausen/cs225FinalProject#1]
Your proposal looks good.  The games are ambitious but you have a good team here and I think you can make it happen.  The only thing I'd like to see added to the proposal is a bit more of a breakdown for the points to specific tasks and functionality in the programs.  @adamdachenhausen @knelligan @le15carl

**Comment by adamdachenhausen** [comment]
@jteresco 
I just added a more specific point breakdown.

**Comment by jteresco** [comment]
Looks good now, thanks.
