### ISSUE TITLE
Program upon start, crashes

### ISSUE THREAD

**Issue by adamdachenhausen** [adamdachenhausen/cs225FinalProject#11]
After start button pressed, all aliens fall out, the red ship gets stuck to the top left, and eventually the program gets stuck and won't close.

**Comment by knelligan** [comment]
Yeah, that is something that happened when I added the alien shooting loop. I described in another issue because I didn't see this one. I commented out for now--if you pull with git, it will work now.

**Comment by adamdachenhausen** [comment]
I'll close this one then.
