### ISSUE TITLE
Alien Shot

### ISSUE THREAD

**Issue by knelligan** [adamdachenhausen/cs225FinalProject#12]
I added the randomized alien shooting (i have a random generator in the alien class run method that returns true when the random number is 0).

Then in threadgraphicscontroller in that paint method I make a call to create an alien laser and to start the alien laser run method in the body of the alien draw loop.

This causes problems and freezes the program, so I commented out the code for now.

**Comment by knelligan** [comment]
I tried to debug this today and it is giving me a lot of trouble. as soon as an alien laser shot is started, the program crashes. I inserted override into paint/run in lasershot class and tried to put in a test run method to see if that was the problem but it

**Comment by knelligan** [comment]
I am going to try to comment out some of the code in alien shot and substitute a block of simpler code to see if any of that solves the problem.  I'm not sure if some of the issue is that there was no run method implemented in alien shot and we are changing instance variables during the paint method a lot.

**Comment by knelligan** [comment]
That was not the problem, it still doesn't work--as soon as i create an array to store alien attacks it causes all sorts of problems.

**Comment by adamdachenhausen** [comment]
I'll try to get the laser animations working by themselves just to make sure that's not the problem.

**Comment by knelligan** [comment]
ok cool, I'm maybe going to separate out into another class just to see if that is part of the problem.

**Comment by knelligan** [comment]
I really think 90% or more of the problem is that we can't call the creation of the alien lasers in threadgraphicscontroller. we also don't seem to be able to create lasers in the alien class run method.

so i'm thinking of maybe creating a method that creates them somehow in the arcademachine class.  maybe creating a run method that mirrors the movement of aliens and shoots from those points. I've tried everything and i i know that it is actually creating a laser object that is breaking the program. I'm still not sure why that is happening.

**Comment by knelligan** [comment]
I got the alien shot to work with the simplified shot I'm going to try the version you made now instead.
