### ISSUE TITLE
Explosions

### ISSUE THREAD

**Issue by knelligan** [adamdachenhausen/cs225FinalProject#13]
I haven't thoroughly looked at this, but when the aliens are hit, the point with the explosion moves up so it looks like the explosion moves up--need to fix this.

Also I need to center explosions still, there is a green one for a missed shot, a red one for the ufo and a white one for the aliens. I might have a different green one for the player ship as well.

Still need the following collision checking:

- when aliens hit player ship (need to fix alien lasers first -- i don't think it's a problem with the alien laser class i think it's a problem with how i am calling it in the threadgraphicscontroller.

- shields need to have collision detection from player and aliens.

- player ship needs a second collision detector if the aliens hit them (that would also kill player).

**Comment by adamdachenhausen** [comment]
I tried to center the explosions on the left point of the laser, but it just moved it farther away for some reason. I'll take a look tomorrow. For reference the explosion is 39px W by 50 px H. I think we might want to tackle the explosion not moving up first, then update where the explosion happens. We might have a sync issue with updating upperLeft here.

**Comment by knelligan** [comment]
Ok, yeah it is tricky! I will look at all of this tomorrow too--i didn't write the code for centering carefully i was just trying to get it to show up, so it shouldn't be too hard.

I am going to look at all of these things tomorrow too. I am done with the project for tonight but I will start working on it again first thing tomorrow.

**Comment by adamdachenhausen** [comment]
Fixed this, all I had to do was pass the laser, instead of a point into checkAlienHit(), and if it was determined to be hit, just stop that laser.
