### ISSUE TITLE
Shield hit damage

### ISSUE THREAD

**Issue by knelligan** [adamdachenhausen/cs225FinalProject#15]
Added a shield check to the threadgraphicscontroller class lines 414 - 431. Can you check the shield checker method: checkShieldHit()?

I tried to set it up but maybe I'm not creating the damage the way you intended.

**Comment by adamdachenhausen** [comment]
It looks like it should work, but the only thing that I don't see is that we aren't starting the shield anywhere. I think we also have to start the shield sections too, but we might want to just call the sections' run from shields run. I'll take a look at this in the morning.

**Comment by knelligan** [comment]
Okay, I'm going to try to get that working now. The shields are started in arcademachine in the "createshields" method, but I didn't ever start the shield section, i wonder if we should start the sections in the constructor of the shield like you did for laser/lasershot classes.
