### ISSUE TITLE
Lives

### ISSUE THREAD

**Issue by knelligan** [adamdachenhausen/cs225FinalProject#16]
I have all of the basic functionality in place but if you are hit by an alien laser (this is controlled by lines 279 - 301 in threadgraphicscontroller and the method checkPlayerHit() starting on line 423 of the same class.

I think that when the laser hits the player it's the same laser hit registering several times but I'm not sure, it would help if someone else could take a look at it.
Thanks!

**Comment by adamdachenhausen** [comment]
I'm looking at this right now, but I was playing and not really that close to an incoming laser, and still lost lives.

**Comment by knelligan** [comment]
yeah i'm kind of stuck on it. we might need to recalculate the logic of how a hit is measured. i don't know though--I'm stuck on it.

**Comment by adamdachenhausen** [comment]
I don't know if I found the problem, but when I tested where getting hit kills, I found that its the body + some space to the right. I added a line in the checkPlayerHit to print out the width, and its 72, but it should only be 40.

**Comment by adamdachenhausen** [comment]
getWidth is returning small+med+large

**Comment by knelligan** [comment]
oh no! that explains it i probably copy pasted! thank you for figuring that out...

**Comment by adamdachenhausen** [comment]
That didn't help much though...

**Comment by knelligan** [comment]
yeah there is something else going on

what i think is happening is that  when a laser hits it's registering the hit for like the whole length of the laser instead of just the point it hits.

**Comment by adamdachenhausen** [comment]
See I would say, just change it to be off upperLeft, but that wouldn't work if its an alien shot.

**Comment by knelligan** [comment]
ok i fixed/pushed the player ship width. i also just tried to force the while loop to break to see if that would stop the loop from registering that multiple lives were lost instead of just one, maybe it's something else causing the problem. I guess we could ask Dr. Teresco.

**Comment by knelligan** [comment]
i wonder if we could try to regenerate the player object after it is killed in that loop based on an instance variable of the class instead. I'm running out of ideas

**Comment by adamdachenhausen** [comment]
The only thing that I could think of, is that the laser is not dying quickly enough, so its possible that we are handling the collision correctly, but we aren't handling the laser stopping and dying correctly. I'll look into this

**Comment by knelligan** [comment]
i just thought of another thing it might be--i think that maybe the laser is creating multiple lasers since it's randomized. I'm going to change alien class to make it only allow for one laser per alien at a time.  I'll try looking at it from that angle
