### ISSUE TITLE
Aliens fire all at once to create a barrage

### ISSUE THREAD

**Issue by adamdachenhausen** [adamdachenhausen/cs225FinalProject#18]
I think we might want to add a cool down to the alien ship firing. I think a similar solution to how I did the player cool down, but with a random.

**Comment by knelligan** [comment]
yeah i do think a few too many are firing--i moved the firing randomizer from the alien class to the tgc paint loop --that was how I got them to not fire like 5 times almost simultaneously from the same alien.  I decreased shot frequency by increasing the random value that would decide whether or not to fire. I will look at how you did the cooldown in the arcade cabinet and try to duplicate!

**Comment by adamdachenhausen** [comment]
I just fixed this by introducing a multiplier into the random number generator, so the number generator produces a larger number, but if we want to make a select difficulty, all we have to do is adjust the multiplier.
