### ISSUE TITLE
How much HP do shields need?

### ISSUE THREAD

**Issue by adamdachenhausen** [adamdachenhausen/cs225FinalProject#2]
Currently I have it set up so its a boolean double array, so they are either damaged or not, but I can change it quite easily.

**Comment by knelligan** [comment]
I think each square within the shield should take maybe 3 hits? is that reasonable? I'm fine with whatever you prefer. Sorry I didn't see this!

**Comment by adamdachenhausen** [comment]
No problem, I will make those changes. Since it has to be a number, it should be easily changeable later.
