### ISSUE TITLE
Image load error (low priority because the image still draws)

### ISSUE THREAD

**Issue by knelligan** [adamdachenhausen/cs225FinalProject#20]
Since I moved the construction of the robber class to gameboard, I get an error (but it still draws the image and it works fine) i don't know if i'm supposed to load the image in a try catch block. I will figure this out later.

**Comment by adamdachenhausen** [comment]
This might be that issue like in FallingSnow, where we were using the image before it was done loading, but you have the imageUpdate method, so I don't know

**Comment by knelligan** [comment]
yeah if i can't figure it out, i'll ask dr teresco. i was thinking of falling snow too--this didn't happen before i called the method in the gameboard class which is weird. i'll have to see if i am doing something else differently

**Comment by knelligan** [comment]
fixed it -- the container was = to null when robber was constructed.
