### ISSUE TITLE
Problem with roads/cities being drawn (how to call/create them)

### ISSUE THREAD

**Issue by knelligan** [adamdachenhausen/cs225FinalProject#25]
I'm trying now to compare a mouse click point to where a point in a road is near (and it's possible i just  am missing something), but I'm having trouble getting to the points stored within roads to check them against where the user clicked.

I'm not sure how to access individual road points and city points.

What I'd like to do is set the Point value of a gamepiece to the point value in either a city or road that was near where the user clicked (maybe it would be easiest to just tell the user to click a midpoint for roads...

If you could take a look it would be a huge help-- I also emailed you more details. Sorry for the trouble--I'm not working in the catan class at this moment so there wouldn't be conflicts.  I'm assigning it to you just so you see it, if you can't get to it that is ok, just let me know.

**Comment by adamdachenhausen** [comment]
Fixed. Whenever the player clicks close enough to a city/road, it will be removed from the "possible list" and transferred to the player list. It is then drawn in the player's color.
