### ISSUE TITLE
Files in repository that should not be there

### ISSUE THREAD

**Issue by jteresco** [adamdachenhausen/cs225FinalProject#3]
.class and .ctxt files should not be added to repositories.  It's a recipe for lots of merge conflicts.  I recommend removing them with "git rm".

**Comment by adamdachenhausen** [comment]
We have a .gitignore , is there a reason that this isn't working?

**Comment by jteresco** [comment]
Is it possible they got in before the .gitignore was in place?

**Comment by adamdachenhausen** [comment]
It is, but I went ahead and removed them manually.
