### ISSUE TITLE
First 3 Alien ships in top left move differently

### ISSUE THREAD

**Issue by adamdachenhausen** [adamdachenhausen/cs225FinalProject#7]
They seem to move slightly faster than all of the other ones, it could just be my PC. I'll try it in the morning on my desktop.

**Comment by knelligan** [comment]
ok I will take a look, I also need to get them to speed up as the progress, I just haven't been successful with that yet.

**Comment by knelligan** [comment]
this isn't happening for me, I'm not sure why that would be.

**Comment by adamdachenhausen** [comment]
It wasn't happening recently, but I think it might have been something with the threading. It also could have just been my PC.
