### ISSUE TITLE
Laser cool down?

### ISSUE THREAD

**Issue by adamdachenhausen** [adamdachenhausen/cs225FinalProject#8]
It is possible to just hold down space, and the laser will spam. We might want to add a cool down to it so every second (or so) the player can fire.

**Comment by knelligan** [comment]
that is a good idea, I'm not sure but I'll try it!

**Comment by knelligan** [comment]
I think that in addition to this we need to do something where the player can shoot and move left/right at the same time--super annoying in games where you can't shoot and move at the same time. I think building in the cooldown and having it detect  when someone holds the spacebar could both be dealt with at the same time.

**Comment by adamdachenhausen** [comment]
I was thinking on how to do that too, I was thinking of using a thread to do this, but I'm not sure. I'm thinking now, that we change the if, else if, ... to just individual if statements.

**Comment by adamdachenhausen** [comment]
I'll try that quick, for the movement.

**Comment by adamdachenhausen** [comment]
That didn't work

**Comment by adamdachenhausen** [comment]
Okay, two ways that I have found to handle multiple inputs:
A. use bit masking 
B. Track the states of keys via booleans like leftIsDown
